AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless Application
Parameters:
  LambdaS3Bucket:
    Type: String
    Description: The S3 bucket where the Lambda deployment package is stored
  LambdaS3Key:
    Type: String
    Description: The S3 key of the Lambda deployment package
  LambdaExecutionRoleArn:
    Type: String
    Description: The ARN of the IAM role that Lambda assumes
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HondaServerlessAppFunction
      Handler: HondaBearingServerless::HondaBearingServerless.Function::FunctionHandler
      Role:
        Ref: LambdaExecutionRoleArn
      Code:
        S3Bucket:
          Ref: LambdaS3Bucket
        S3Key:
          Ref: LambdaS3Key
      Runtime: dotnet8
      MemorySize: 256
      Timeout: 30
Outputs:
  LambdaFunctionArn:
    Value:
      Fn::GetAtt:
      - MyLambdaFunction
      - Arn
    Description: ARN of the Lambda function
